name: ci

on: [push]

jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: "18.18.0"

            - name: Setup yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install

            - name: Compile
              run: yarn build

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: "18.18.0"

            - name: Setup yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install

            - name: Check for formatting issues
              run: yarn prettier . --check --ignore-unknown

            - name: Run tests
              run: yarn test

  release:
    needs: [compile, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.0"

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build the package
        run: yarn build

      - name: Pack the module
        run: npm pack --pack-destination .

      - name: Get version from package.json
        id: get-version
        run: echo "version=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get-version.outputs.version }}
          tag_name: ${{ steps.get-version.outputs.version }}
          files: ./*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish:
        needs: [compile, test]
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: "18.18.0"

            - name: Setup yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Publish to npm
              run: |
                  npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
                  if [[ ${GITHUB_REF} == *alpha* ]]; then
                    npm publish --access public --tag alpha
                  elif [[ ${GITHUB_REF} == *beta* ]]; then
                    npm publish --access public --tag beta
                  else
                    npm publish --access public
                  fi
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
